apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-app-deployment
  labels:
    app: rs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rs-app
  template:
    metadata:
      labels:
        app: rs-app
    spec:
      containers:
        - name: rs-app-container
          image: 381491906321.dkr.ecr.us-east-1.amazonaws.com/rulestudio-javapp:1.0
          ports:
            - containerPort: 80
